name: Generate bounties data
run-name: ${{ github.actor }} 🚀
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */1 * * *'

env:
  ALCHEMY_APIKEY: ${{ secrets.ALCHEMY_APIKEY }}
  INFURA_APIKEY: ${{ secrets.INFURA_APIKEY }}

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v2
        with:
          go-version: '1.22.1'

      - run: go run ./main.go

       # Commit all changed files back to the repository
      - uses: stefanzweifel/git-auto-commit-action@v4

